dist: bionic
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # install zeromq
  - sudo apt-get update
  - git clone https://github.com/zeromq/libzmq.git
  - cd libzmq
  - mkdir build
  - cd build
  - cmake ..
  - sudo make -j4 install
  - cd ../../
  # install cppzmq
  - git clone https://github.com/zeromq/cppzmq.git
  - cd cppzmq/
  - mkdir build
  - cd build
  - cmake ..
  - sudo make -j4 install
  - cd ../../

  #  install dlib
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install libdlib-dev

  - sudo apt-get install g++-8 cmake -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential cmake unzip pkg-config
  - sudo apt-get install -y libjpeg-dev libpng-dev libtiff-dev
  - sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
  - sudo apt-get install -y libxvidcore-dev libx264-dev
  - sudo apt-get install -y libgtk-3-dev
  - sudo apt-get install -y libatlas-base-dev gfortran
  - sudo apt-get install -y python3-dev python-dev

  - git clone -b 4.1.0 https://github.com/opencv/opencv.git
  - git clone -b 4.1.0 https://github.com/opencv/opencv_contrib.git
  - cd opencv

  # Create a new 'build' folder.
  - mkdir build
  - cd build

  # Set build instructions for Ubuntu distro.
#  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules -D BUILD_EXAMPLES=OFF ..
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
  # Run 'make' with four threads.
  - make -j$(nproc)

  # Install to OS.
  - sudo make install

  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

  - sudo ldconfig
  - echo "OpenCV installed."
  - cd ../../

before_script:
  - ls
  - gcc --version
  - g++ --version
  - cmake --version

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
      - curl -f -T cod-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ustanislavkuskov:$BINTRAY_API_KEY "https://api.bintray.com/content/stanislavkuskov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/cod-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"